[tools]
awscli = "latest"
fd = "latest"
fzf = "latest"
go = "latest"
kubectl = "latest"
neovim = "latest"
node = "lts"
python = "latest"
ripgrep = "latest"
starship = "latest"
terraform = "latest"
terramate = "latest"
uv = "latest"
yq = "latest"
usage = "latest"
luajit = "latest"
