format = """
$os$directory$git_branch$git_status$fill$cmd_duration$status
$character"""

add_newline = false

[fill]
symbol = " "

[os]
disabled = false
format = "[$symbol]($style) "

[directory]
style = "blue"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = " "
style = "green"
format = "[$symbol$branch]($style) "

[git_status]
style = "green"
format = "([$all_status$ahead_behind]($style) )"
conflicted = "[~$count](red) "
ahead = "[⇡$count](green) "
behind = "[⇣$count](green) "
untracked = "[?$count](blue) "
modified = "[!$count](yellow) "
staged = "[+$count](yellow) "

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"
vicmd_symbol = "[❮](green)"

[cmd_duration]
min_time = 3000
format = "took [$duration](yellow) "

[status]
disabled = false
format = "[$symbol]($style) "
symbol = "✘ "
style = "red"

[aws]
format = "on [$symbol($profile )(\\($region\\) )]($style)"
style = "yellow"

[nodejs]
format = "via [$symbol($version )]($style)"
style = "green"

[python]
format = "via [$symbol($version )(\\($virtualenv\\) )]($style)"
style = "cyan"

[golang]
format = "via [$symbol($version )]($style)"
style = "cyan"

[rust]
format = "via [$symbol($version )]($style)"
style = "red"

[terraform]
format = "via [$symbol($workspace )]($style)"
style = "purple"
