[settings]
experimental = true

[settings.npm]
bun = true

[tools]
awscli = "latest"
fd = "latest"
fzf = "latest"
kubectl = "latest"
neovim = "latest"
python = "latest"
ripgrep = "latest"
starship = "latest"
terraform = "latest"
terramate = "latest"
uv = "latest"
yq = "latest"
usage = "latest"
luajit = "latest"
"conda:mosh" = "latest"
tmux = "latest"
gh = "latest"
opencode = "latest"
lazygit = "latest"
bun = "latest"
bat = "latest"
node = "25.2.1"
markdownlint-cli2 = "0.20.0"
