[settings]
experimental = true

[settings.npm]
bun = true

[tools]
awscli = "latest"
fd = "latest"
fzf = "latest"
go = "latest"
kubectl = "latest"
neovim = "latest"
node = "lts"
python = "latest"
ripgrep = "latest"
starship = "latest"
terraform = "latest"
terramate = "latest"
uv = "latest"
yq = "latest"
usage = "latest"
luajit = "latest"
"conda:mosh" = "latest"
tmux = "latest"
gh = "latest"
opencode = "latest"
lazygit = "latest"
bun = "latest"
"go:go.bbkane.com/fling" = "1d695d156a38f25486f735ebc4dc3510a3b0f479"
